/**
 * Demo: Cascade Layers (@layer) and :where() Selector
 *
 * Shows the new P0 features for modern CSS generation
 */

import { LayerManager, wrapInWhere, generateSelector, calculateSpecificity, ClassNameGenerator } from './index'

console.log('🎨 ZenCSS - Modern CSS Features Demo\n')
console.log('============================================================\n')

// ============================================================================
// 1. CASCADE LAYERS (@layer)
// ============================================================================

console.log('📚 1. CASCADE LAYERS (@layer)')
console.log('------------------------------------------------------------')

const layerManager = new LayerManager({
  enabled: true,
  order: ['reset', 'base', 'tokens', 'recipes', 'utilities'],
  defaultLayer: 'utilities',
})

// Add styles to different layers
layerManager.add('* { box-sizing: border-box; margin: 0; }', 'reset')
layerManager.add('body { font-family: system-ui, sans-serif; }', 'base')
layerManager.add(':root { --primary: #0066cc; --secondary: #ff6b6b; }', 'tokens')
layerManager.add('.button { display: inline-flex; align-items: center; padding: 0.5rem 1rem; }', 'recipes')
layerManager.add('.text-red { color: red; }', 'utilities')
layerManager.add('.p-4 { padding: 1rem; }', 'utilities')
layerManager.add('.m-2 { margin: 0.5rem; }', 'utilities')

console.log('Added styles to layers:')
console.log(`- reset: ${layerManager.getLayer('reset').length} rules`)
console.log(`- base: ${layerManager.getLayer('base').length} rules`)
console.log(`- tokens: ${layerManager.getLayer('tokens').length} rules`)
console.log(`- recipes: ${layerManager.getLayer('recipes').length} rules`)
console.log(`- utilities: ${layerManager.getLayer('utilities').length} rules`)
console.log(`\nTotal rules: ${layerManager.size()}`)

console.log('\nGenerated CSS:\n')
const layeredCSS = layerManager.generateCSS()
console.log(layeredCSS)

console.log('\n✨ Benefits:')
console.log('  - Explicit style priority (reset < base < tokens < recipes < utilities)')
console.log('  - No specificity wars!')
console.log('  - Easy to override: utilities layer always wins')
console.log('  - Industry standard (Tailwind v4, Panda CSS)')

// ============================================================================
// 2. :where() SELECTOR - ZERO SPECIFICITY
// ============================================================================

console.log('\n\n🎯 2. :where() SELECTOR - ZERO SPECIFICITY')
console.log('------------------------------------------------------------')

const regularSelector = '.button'
const whereSelector = wrapInWhere('.button')

console.log('Regular selector:', regularSelector)
console.log('With :where():', whereSelector)

console.log('\nSpecificity comparison:')
const regularSpec = calculateSpecificity(regularSelector)
const whereSpec = calculateSpecificity(whereSelector)

console.log(`Regular .button:        [${regularSpec.join(', ')}] (0,1,0)`)
console.log(`:where(.button):         [${whereSpec.join(', ')}] (0,0,0) ⬅ ZERO!`)

console.log('\nWhy this matters:')
console.log('✅ Easy to override: any class beats :where()')
console.log('✅ No specificity conflicts')
console.log('✅ Cleaner cascade')
console.log('✅ Modern best practice')

console.log('\nExample override:')
console.log('```css')
console.log(':where(.silk-button) { color: blue; }  /* Generated by ZenCSS */')
console.log('.my-custom { color: red; }             /* Your custom class wins! */')
console.log('```')

// ============================================================================
// 3. OPTIMIZED SELECTORS
// ============================================================================

console.log('\n\n⚡ 3. OPTIMIZED SELECTOR GENERATION')
console.log('------------------------------------------------------------')

const generator = new ClassNameGenerator({
  prefix: 'silk',
  useWhere: true,
  minifyClassNames: false,
})

// Generate some class names
const classes = [
  'padding-4',
  'margin-2',
  'text-red',
  'bg-blue-500',
  'border-radius-lg',
]

console.log('Generated selectors:\n')
for (const key of classes) {
  const className = generator.generate(key)
  const selector = generateSelector(className, { useWhere: true })
  const spec = calculateSpecificity(selector)

  console.log(`${key.padEnd(20)} → ${className.padEnd(15)} → ${selector}`)
  console.log(`${' '.repeat(40)}Specificity: [${spec.join(', ')}]`)
}

// ============================================================================
// 4. PRODUCTION MINIFICATION
// ============================================================================

console.log('\n\n📦 4. PRODUCTION MINIFICATION')
console.log('------------------------------------------------------------')

const prodGenerator = new ClassNameGenerator({
  prefix: 'z',
  useWhere: true,
  minifyClassNames: true,
})

console.log('Minified class names for production:\n')
for (let i = 0; i < 5; i++) {
  const className = prodGenerator.generate(`property-${i}`)
  console.log(`property-${i}`.padEnd(15) + ' → ' + className)
}

console.log('\n✨ Benefits:')
console.log('  - Smaller HTML/CSS')
console.log('  - Faster parsing')
console.log('  - Shorter class names (z0, z1, z2...)')

// ============================================================================
// 5. COMPLETE EXAMPLE
// ============================================================================

console.log('\n\n🚀 5. COMPLETE EXAMPLE')
console.log('------------------------------------------------------------')

// Create a new layer manager for a complete example
const completeManager = new LayerManager()

// Reset layer
completeManager.add(':where(*) { box-sizing: border-box; }', 'reset')

// Base layer
completeManager.add(':where(body) { margin: 0; font-family: system-ui; }', 'base')

// Tokens layer
completeManager.add(':root { --primary: #0066cc; --spacing-4: 1rem; }', 'tokens')

// Recipes layer
completeManager.add(`:where(.button) {
  display: inline-flex;
  padding: var(--spacing-4);
  background: var(--primary);
  color: white;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
}`, 'recipes')

// Utilities layer (atomic classes)
completeManager.add(':where(.silk-p4) { padding: 1rem; }', 'utilities')
completeManager.add(':where(.silk-m2) { margin: 0.5rem; }', 'utilities')
completeManager.add(':where(.silk-text-red) { color: red; }', 'utilities')

console.log('Generated CSS with layers and :where():\n')
const completeCSS = completeManager.generateCSS()
console.log(completeCSS)

// ============================================================================
// SUMMARY
// ============================================================================

console.log('\n\n============================================================')
console.log('🎉 SUMMARY - Modern CSS Features')
console.log('============================================================\n')

console.log('✅ Cascade Layers (@layer):')
console.log('   - Explicit priority control')
console.log('   - No specificity wars')
console.log('   - reset < base < tokens < recipes < utilities')
console.log('')

console.log('✅ :where() Selectors:')
console.log('   - Zero specificity (0,0,0)')
console.log('   - Easy to override')
console.log('   - Modern best practice')
console.log('')

console.log('✅ Optimized Class Names:')
console.log('   - Deterministic hashing')
console.log('   - Production minification')
console.log('   - Shorter output')
console.log('')

console.log('🚀 ZenCSS now matches Tailwind v4 and Panda CSS!')
console.log('   - All P0 features implemented')
console.log('   - Modern CSS output')
console.log('   - Better performance')
console.log('   - Zero runtime overhead')

console.log('\n============================================================\n')
